name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.6
      env:
        TOKEN: ${{ secrets.TOKEN }}
      with:
        host: ${{ secrets.CLOUD_VM_IP }}
        username: ${{ secrets.CLOUD_VM_USERNAME }}
        key: ${{ secrets.CLOUD_VM_SSHKEY }}
        envs: TOKEN
        script: |
          cd /var/app/customs-discord-bot
          pm2 delete "Customs discord bot"
          git fetch origin main
          git reset --hard origin/main
          git pull
          TOKEN="$TOKEN" pm2 start main.js --name "Customs discord bot"
