name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.6
      with:
        key: ${{secrets.CLOUD_VM_SSHKEY}}
        host: ${{secrets.CLOUD_VM_IP}}
        username: ${{secrets.CLOUD_VM_USERNAME}}
        script: |
          pm2 delete all
          cd /var/app/customs-discord-bot
          sudo git pull
          sudo npm install
          pm2 start npm -- start
